packages:
  - mastracode
  - docs
  - packages/_vendored/*
  - packages/*
  - deployers/*
  - stores/*
  - voice/*
  - workflows/*
  - workspaces/*
  - server-adapters/*
  - pubsub/*
  - client-sdks/*
  - integrations/*
  - auth/*
  - observability/*
  - explorations/longmemeval
  - explorations/agent-builder-gh-repro
  - e2e-tests/client-js/_test-utils
  - e2e-tests/client-js/zod-v3
  - e2e-tests/client-js/zod-v4
  - e2e-tests/workspace-compat

catalog:
  "@microsoft/api-extractor": "^7.56.3"
  "@vitest/coverage-v8": 4.0.18
  "@vitest/ui": 4.0.18
  typescript: ^5.9.3
  vitest: 4.0.18
  zod: ^4.3.6

onlyBuiltDependencies:
  - "@vvago/vale"

patchedDependencies:
  "@changesets/get-dependents-graph": patches/@changesets__get-dependents-graph.patch
